__author__ = "Michael Halls-Moore"
__copyright__ = "Copyright 2016"
__license__ = "MIT"
__version__ = "0.0.1"
__maintainer__ = "mhallsmoore"
__email__ = ""
__status__ = "Development"
__url__ = "https://github.com/mhallsmoore/qstrader"
